### PR TITLE
feat: create action bar component

### PR DESCRIPTION
**Pull request by luqven**
## Description
This PR creates the `ActionBar />` component. This component houses the pagination and "add image" buttons. This component is meant to replace the current footer in the `<ImageGallery />` component.`

# Before
Footer had buttons that styling did not match comps.

# After
Footer is now a separate component. It's styling matches the design comps.

### Future work
 - Render more images in the gallery so the footer isn't so far away
 - Find a way to make the modal smaller, it's confusing to have the buttons so far away.

# Steps to test
- pull down this branch
- run `npm run start`
- open contenful staging and click on "add image"
- select a source
- see the new footer after scrolling

# 🖼️  Screenshots
> Footer before
footer-before

> Footer after
action-bar-component

https://user-images.githubusercontent.com/16711614/198703327-fd60792d-7dd9-46bd-92bb-04c9775b77e5.mov

## Checklist

- [x] Read the [contributing guidelines](CONTRIBUTING.md).
- [x] Each commit follows the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) spec format.
- ~[ ] Update the readme (if applicable).~
- ~[ ] Update or add any necessary API documentation (if applicable)~
- [ ] All existing unit tests are still passing (if applicable).

- [ ] Add some [steps](#steps-to-test) so we can test your bug fix or feature (if applicable).
- [ ] Add new passing unit tests to cover the code introduced by your PR (if applicable).
- [ ] Any breaking changes are specified on the commit on which they are introduced with `BREAKING CHANGE` in the body of the commit.
- [ ] If this is a big feature with breaking changes, consider opening an issue to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.

### CODE REVIEW

**Comment by luqven** [comment]
Current dependencies on/for this PR:
* next
  * **PR #140** <a href="https://app.graphite.dev/github/pr/imgix/contentful/140" target="_blank">Graphite</a> 
    * **PR #139** <a href="https://app.graphite.dev/github/pr/imgix/contentful/139" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/imgix/contentful/139?utm_source=stack-comment).

**Comment by sherwinski** [comment]
This looks 🔥 🔥 @luqven 

Regarding this point:
> Find a way to make the modal smaller, it's confusing to have the buttons so far away.

You might want to try flipping the `allowHeightOverflow` flag where we invoke [openCurrentApp](https://github.com/imgix/contentful/blob/l%2Fupdate-react/src/components/Field/Field.tsx#L34) and see if that helps.

**Comment by luqven** [comment]
> This looks 🔥 🔥 @luqven
> 
> Regarding this point:
> 
> > Find a way to make the modal smaller, it's confusing to have the buttons so far away.
> 
> You might want to try flipping the `allowHeightOverflow` flag where we invoke [openCurrentApp](https://github.com/imgix/contentful/blob/l%2Fupdate-react/src/components/Field/Field.tsx?rgh-link-date=2022-10-28T23%3A13%3A08Z#L34) and see if that helps.

So this works but it 1) chops off the grid of images unless over `overflow: scroll` in which case pagination with buttons seems silly and 2) as a result of 1. breaks the absolute positioning of the action bar :(

**Comment by luqven** [comment]
Ok after spending ~45 minutes trying to get the window to behave it's clear some more involved refactoring is needed to get the dimensions how we want them.

The short of it is, we've nested components in such a way that we're getting in our own way when it comes to being able to control the top and bottom bar positioning.

I'm going to revisit resizing the window down the road.

**Review by sherwinski — APPROVED** [review]

**Comment by luqven** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/imgix/contentful/139?utm_source=stack-comment).


Job Reference: yGgqIySrcaAmVh8uxOCg

**Pull request merged**
