### PR TITLE
feat: add upload success and error notifications

### PR DESCRIPTION
**Pull request by luqven**
## Description
This commit adds notifications on upload success or failure. It also correctly handles the error response from the upload API call. Before the call was wrapped in a try-catch and a `.then()` call. The error never made it to the `catch`.`

## Steps to test
1. Pull down
2. Run `npm run start`
3. Open contentful staging
4. Click add image
5. Select a source OR Select a source without upload permissions
6. Upload and image
7. See success OR See error

## 🖼️ Screenshots

https://user-images.githubusercontent.com/16711614/200992531-25d29c6f-c715-4069-b235-fa1a23ca9522.mov

https://user-images.githubusercontent.com/16711614/200992539-97ad7530-1bbb-40e9-9859-260dec865782.mov

https://user-images.githubusercontent.com/16711614/200992593-8d192f08-5368-4a9d-b83b-f6d1b4dadb09.mov

## Checklist

- [x] Each commit follows the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) spec format.
- [x] All existing unit tests are still passing (if applicable).
- [x] Add some [steps](#steps-to-test) so we can test your bug fix or feature (if applicable).

### CODE REVIEW

**Comment by luqven** [comment]
Current dependencies on/for this PR:
* next
  * **PR #156** <a href="https://app.graphite.dev/github/pr/imgix/contentful/156" target="_blank">Graphite</a> 
    * **PR #158** <a href="https://app.graphite.dev/github/pr/imgix/contentful/158" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/imgix/contentful/158?utm_source=stack-comment).

**Review by sherwinski — APPROVED** [review]
LGTM save for one question.

In the first screen cap (`error-examples.mov`), the error emitted tells users to update their keys. AFAIK there isn't a `upload`-specific permission on API keys (unless what I'm looking for is `Asset Manager Edit`).
I just want to make sure that we're giving users actionable feedback here even if we're just passing along the message returned by the server.

**Comment by luqven** [comment]
> (unless what I'm looking for is `Asset Manager Edit`).

This is exactly it. Can't upload without that permission set on the key.

**Comment by sherwinski** [comment]
Fair enough, I'm happy to move forward with this as is and we can revisit if we receive feedback that the error isn't clear enough.

**Pull request merged**
